### ISSUE TITLE
better Crashlytics

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#44]
As this problem is not easily reproducible, add some more information to the crashlytics reports:
https://firebase.google.com/docs/crashlytics/customize-crash-reports

- [x] log the user
- [x] log current internet connection state
- [x] log seconds since last connection state change
- [x] log if a sync is currently happening
- [ ] ~~log for how long the sync is taking or how long the last sync took~~

**Comment by ZhangNemo34** [comment]
1. when should i log the user?
should i log user's email when user login to app?
2. when should i log the internet connection state?
should i log the state every time when connection state is changed?
3. 
4. 
5. should calculate duration of current sync?
run timer every second to calculate duration, something like this?

**Comment by mmatiaschek** [comment]
https://firebase.google.com/docs/crashlytics/customize-crash-reports

1. when starting the App, after successful login
2. listen for connection changes - log: what the connection state was and what it changed to

you can leave 5.
