### ISSUE TITLE
growth chart improvements

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#67]
- [x] measure line should only show measures of type: "manual"

## x and y labels

- [ ] set labels for x and y-axis
  - age --> days
  - height --> cm
  - weight --> kg
  - MUAC --> cm
  - Head circumference --> cm

## implement the other charts

- [x] "Age / Weight" --> "Weight-for-age"
- [ ] [Weight-for-age (girls)](http://www.who.int/childgrowth/standards/wfa_girls_p_exp.txt)
- [ ] [Weight-for-age (boys)](http://www.who.int/childgrowth/standards/wfa_boys_p_exp.txt)

- [x] "Height / Weight --> "Weight-for-height"
- [ ] [Weight-for-height (girls)](http://www.who.int/childgrowth/standards/wfh_girls_p_exp.txt)
- [ ] [Weight-for-height (boys)](http://www.who.int/childgrowth/standards/wfh_boys_p_exp.txt)

- [ ] new chart "Weight-for-length"
- [ ] [Weight-for-length (girls)](http://www.who.int/childgrowth/standards/wfl_girls_p_exp.txt)
- [ ] [Weight-for-length (boys)](http://www.who.int/childgrowth/standards/wfl_boys_p_exp.txt)

- [ ] new chart "Head circumference-for-age"
- [ ] [Head circumference-for-age (girls)](http://www.who.int/childgrowth/standards/second_set/hcfa_girls_p_exp.txt)
- [ ] [Head circumference-for-age (boys)](http://www.who.int/childgrowth/standards/second_set/hcfa_boys_p_exp.txt)

- [ ] new chart "Arm circumference-for-age"
- [ ] [Arm circumference-for-age (girls)](http://www.who.int/childgrowth/standards/second_set/acfa_girls_p_exp.txt)
- [ ] [Arm circumference-for-age (boys)](http://www.who.int/childgrowth/standards/second_set/acfa_boys_p_exp.txt)

**Comment by ZhangNemo34** [comment]
1. new chart "Weight-for-length"
I don't understand which field of measure will match to length.
Currently we have scan date, height, weight, muac, head circumference values in the measure

**Comment by ZhangNemo34** [comment]
2. I think "Height-for-age" chart is missing.
Otherwise, "Weight-for-height" and "Weight-for-length" will be same chart.
