### ISSUE TITLE
growth chart over-expanded

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#70]
- [ ] check qr code v132-test1

the growth chart is over-expanded because of the scan measurement.
scan measurement should be current timestamp / days of age

![image](https://user-images.githubusercontent.com/3010105/42415291-a7b8f1f2-8249-11e8-9be3-b362fc4e5f7c.png)

**Comment by ZhangNemo34** [comment]
please check birthday in personal fragment.
birthday could be 01/01/1970
if we calculate age in days, it will be over 15000
that was the problem

**Comment by mmatiaschek** [comment]
That is a big problem, it also happens in production that the birthday is set to 0!
